spring:
    application:
        name: simplemetershare

    datasource:
        url: jdbc:postgresql://localhost:5433/simplemeter_db
        username: test_user
        password: testpass

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
server:
    port: 8081

