spring:
    application:
        name: simplemetershare
    datasource:
        url: jdbc:postgresql://localhost:5432/simplemeter_db
        username: meter_admin
        password: supersecurepassword
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
